version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y jq
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u3x3w5q6
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t aws-ecr .
      - docker tag aws-ecr:latest public.ecr.aws/u3x3w5q6/aws-ecr:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/u3x3w5q6/aws-ecr:latest
      - echo Writing image definitions file...
      - printf '[{"name":"nginx-container","imageUri":"%s"}]' public.ecr.aws/u3x3w5q6/aws-ecr:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
